### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by chappk** [bayesian-object-tracking/dbot#5]
Dear Jan,

This is my setup:
gcc version 5.4.0
Eigen version 3.3.4
Ros Kinetic
CUDA Version 8.0.61

I followed the getting started README.md, but unfortunately, it doesn't compile with this setup.
I get this following error:

`/usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:960:8: error: ‘Alignment’ is not a member of ‘Eigen::internal::evaluator<Eigen::VectorBlock<Eigen::Matrix<double, -1, 1>, 12> >’
`
`/usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:984:40: error: ‘Flags’ is not a member of ‘Eigen::internal::evaluator<Eigen::VectorBlock<Eigen::Matrix<double, -1, 1>, 12> >’
`
`/usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:960:8: error: ‘CoeffReadCost’ is not a member of ‘Eigen::internal::evaluator<Eigen::VectorBlock<Eigen::VectorBlock<Eigen::Matrix<double, -1, 1>, 12>, 6> >’
`
`fl/include/fl/distribution/gaussian.hpp:464:37: error: no match for ‘operator-’ (operand types are ‘fl::Real {aka double}’ and ‘Eigen::internal::enable_if<true, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, 1, 1, 0, 1, 1> >, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double, double>, const Eigen::Matrix<double, 1, 1, 0, 1, 1>, const Eigen::Matrix<double, 1, 1, 0, 1, 1> > > >::type {aka const Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, 1, 1, 0, 1, 1> >, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double, double>, const Eigen::Matrix<double, 1, 1, 0, 1, 1>, const Eigen::Matrix<double, 1, 1, 0, 1, 1> > >}’)
             return log_normalizer() - 0.5
`

Do you have any idea or solution for this kind of error?

Regards

**Comment by mmatl** [comment]
I'm having an identical problem as well.

**Comment by mmatl** [comment]
@chappk I was able to fix this error by installing Eigen 3.2.10. It seems something changed between the 3.2 and 3.3 releases that broke this repo.

**Comment by chappk** [comment]
@mmatl Okay, thank you for your feedback.

**Comment by cassinaj** [comment]
The current version no longer works with Eigen 3.3.x. Despite the claims that this reported issue only persists for Eigen 3.3.0 - Eigen3.3.3, I still can reproduces this error on Eigen 3.3.4 as mentioned @mmatl . The issue lies in EurlerBase and requires a fix or re-implementation.  I will get to that as soon as I can. For the time being a workaround is to installing Eigen 3.2.x locally ~/.local. The master branch now enforces to use Eigen3.2.

**Comment by pkr97** [comment]
In order to install Eigen 3.2.10, download http://bitbucket.org/eigen/eigen/get/3.2.10.tar.bz2, then run:

$ cd projects/tracking/src

download using 

$ wget http://bitbucket.org/eigen/eigen/get/3.2.10.tar.bz2

$ tar -xf 3.2.10.tar.bz2
$ cd eigen-eigen-b9cd8366d4e8
$ mkdir build
$ cd build
$ cmake ..
$ sudo make install

cd projects/tracking/
rm -r devel
rm -r build
rm src/CMakeLists.txt
catkin_make

Now the package should compile without any problem.

Cheers,
Prasanna

**Comment by amichlee** [comment]
I think we should reopen this until the getting started read.me is updated.

**Comment by jbohg** [comment]
Updated!
Best, Jeannette
